const meds = ['Neomicina', 'Bacitracina', 'Cloranfenicol',
    'Oxaciclina', 'Amoxicilina', 'Ampicilina', 'Benzilpenicilina Potássica',
    'Procaína', 'Benzetacil', 'Benzatina', 'Benzilpenicilina G potássica',
    'Piperaciclina', 'Tazobactam', 'Imipenen', 'Cilastatina', 'Cefalotina',
    'Cefalexina', 'Cefazolina', 'Ceftazidima', 'Ceftriaxona', 'Cefotaxima',
    'Cefepima', 'Vancomicina', 'Clindamicina', 'Eritromicina', 'Azitromicina',
    'Ciprofloxacino', 'Levofloxacina', 'Norfloxacino', 'Sulfametazol', 'Trimeptoprima',
    'Sulfadiazina de prata', 'Doxiciclina', 'Aztreonam', 'Rifampicina',
    'Nistatina', 'Fluconazol', 'Anfotericina B', 'Cetoconazol', 'Mebendazol',
    'Metronidazol', 'Piperazina', 'Thiabendazol', 'Albendazol', 'Aciclovir',
    'Alopurinol', 'Cetoprofeno', 'Tenoxicam', 'Diclofenaco', 'Acetato de betametazona',
    'Fosfato dissódico de betametasona', 'Dexametasona', 'Dexclorfeniramina',
    'Hidrocortisona', 'Metilprednisolona', 'Prednisona', 'Dipropionato Betametasona',
    'Fosfato dissódico betametasona', 'Acetato de Medroxiprogesterona',
    'Metilergometrina', 'Misoprostol', 'Piperidolato', 'Hisperidina', 'Furosemida',
    'Manitol', 'Espironolactona', 'Hidroclorotiazida', 'Cloranfenicol succinato',
    'Tobramicina', 'Polimixina B', 'Neostigmina', 'Fluoresceína', 'Iopamidol',
    'Sais do ácido ioxitalâmico', 'Diatrizoato de Sódio', 'Sulfato de Bário',
    'Verapamil', 'Anlodipino', 'Diltiazem', 'Propranolol', 'Metoprolol',
    'Atenolol', 'Carvedilol', 'Amiodarona', 'Nifedipina', 'Dinitrato de Isossorbida',
    'Mononitrato de Isossorbida', 'Nitroglicerina', 'Nitroprussiato de Sódio',
    'Metildopa', 'Clonidina', 'Captopril', 'Hidralazina', 'Losartan', 'Cilostazol',
    'Nimodipino', 'Cinarizina', 'Digoxina', 'Ranitidina', 'Omeprazol', 
    'Metoclopramida', 'Domperidona', 'Dimenidrato', 'Escopolamina',
    'Dimeticona', 'Lactulose', 'Fosfato de sódio monobásico e dibásico',
    'Bisacodil', 'Poliestirenosulfonato de Cálcio', 'Rosuvastatina',
    'Sinvastatina', 'Aspirina', 'Heparina', 'Salicilato de dietilamina',
    'Warfarina', 'Acido Tranexâmico', 'Fitomenadiona', 'Clopidogrel',
    'Enoxaparina', 'Albumina Humana', 'Metformina', 'Glibenclamida',
    'Dipirona', 'Paracetamol', 'Codeína', 'Carbamazepina', 'Clonazepan',
    'Diazepan', 'Fenitoína', 'Fenobarbital', 'Fluoxetina', 'Amitriptilina',
    'Dexclorfeniramina', 'Prometazina', 'Butirofenona', 'Clorpromazina', 
    'Haloperidol', 'Clorpromazina', 'Tioridazina', 'Pipotiazina', 
    'Trifluoperazina', 'Tramadol', 'Piracetam', 'Salbutamol', 'Fenoterol',
    'Brometo de Ipratrópico', 'Aminofilina', 'Ambroxol', 'Iodeto de Potássio',
    'Benzoato de benzila', 'Deltametrina', 'Metronidazol', 'Lisozima',
    'Carbamazepina', 'Valproato de sódio', 'Acido Valproico', 'Pregabalina',
    'Topiramato', 'Levetiracetam', 'Gabapentina', 'Oxcarbazepina', 'Lamotrigina',
    'Primidona', 'Vigabatrina', 'Lacosamida', 'Ibuprofeno', 'Nimesulida', 
    'Cetoprofeno', 'Cafeína', 'Indometacina', 'Acido Mefenâmico', 'Piroxicam',
    'Celecoxibe', 'Etoricoxibe'
]

export default meds;